### ISSUE TITLE
Teensy LC (kintlc) QMK support

### ISSUE THREAD

**Issue by stapelberg** [kinx-project/kint#1]

**Comment by stapelberg** [comment]
I’ll close this as there hasn’t been any user interest in the `kintlc` variant. Please describe in this issue if/why you’re interested in that model, instead of e.g. the `kint40` or `kint41`.

**Comment by aleb** [comment]
I did it

TODO: update the documentation.

**Comment by stapelberg** [comment]
Hooray 🎉 I have updated the README to link to the now-merged PR until QMK does another release.
