### ISSUE TITLE
Best way to connect thumb keys on k500

### ISSUE THREAD

**Issue by ecraven** [kinx-project/kint#11]
I've had a close look at the k500, I think I can probably unsolder the directly soldered connections for the thumb keys. You've kindly provided pin headers on your board, but is there some nice way to have a connector, not directly solder things together?
Thanks for any help with these questions ;)

**Comment by stapelberg** [comment]
On the KB500, your best bet is to cut the cable (don’t bother unsoldering) and solder each pin to a pin header, like so:

![image](https://user-images.githubusercontent.com/55506/91085030-1e184a00-e64d-11ea-9a3d-1f8d6d84e9af.png)

**Comment by ecraven** [comment]
great, that's what I've done, it works very well. Thanks!

**Comment by jcbird** [comment]
Sorry to comment on a closed issue. But could you send a link to the exact part you used? Is this just a female header with the pins soldered to the pcb? Thank you so much!

**Comment by stapelberg** [comment]
Yep, that’s all there is to it.

https://www.digikey.ch/product-detail/en/PPTC241LFBN-RC/S7022-ND/810162 is the part I used last time.

**Comment by jcbird** [comment]
Thank you!

**Comment by MrDeerly** [comment]
Sorry to dig out this old thread again, but there is still some unclarity for me. 

Are the female connectors mentioned above plugged into the [Würth 61301011121](https://octopart.com/61301011121-w%C3%BCrth+elektronik-18818159?r=sp) and soldered to the cable, or are the connectors soldered to the board and the cable just plugged in? 

In addition to that, would it be an option to solder the cable directly to the pin headers (i guess that's not what they're here for), or the board? 

Last but not least, do you have any tips on how to strip the cable for the thumb keys? :) 

Thanks in advance!

**Comment by thatdutchguy** [comment]
In case someone else is wondering, I just went through this (kb500 usb) and I'll share my experiences:

> Sorry to dig out this old thread again, but there is still some unclarity for me.
> 
> Are the female connectors mentioned above plugged into the [Würth 61301011121](https://octopart.com/61301011121-w%C3%BCrth+elektronik-18818159?r=sp) and soldered to the cable, or are the connectors soldered to the board and the cable just plugged in?

They are soldered to the cable, then plug into the pin headers on the KinT PCB.
 
> > `[kinT] --soldered-- [male headers] --plugged-- [female headers] --soldered-- [stock cable] --soldered-- [PCB]`

Yes, I think that's the way it is intended to be used.

> > `[kinT] --soldered-- [female headers] --plugged-- [stock cable] --soldered-- [PCB]`

The wires are pretty thin, so I don't think this would work well.

> In addition to that, would it be an option to solder the cable directly to the pin headers (i guess that's not what they're here for), or the board?

> > `[kinT] --soldered-- [male headers] --soldered-- [stock cable] --soldered-- [PCB]`
> > OR
> > `[kinT] --soldered-- [stock cable] --soldered-- [PCB]`

I suppose this would work but it would be kind of cumbersome/harder than using the female headers.

> Last but not least, do you have any tips on how to strip the cable for the thumb keys? :)

I cut into the strip lengthwise next to each wire a bit, then used a simple wire stripper (see images below). It's not elegant but it works 🙂.

![IMG_6746](https://user-images.githubusercontent.com/209150/227803732-2d1588ad-41ef-449f-bf61-a390b99836fa.jpeg)
![IMG_6747](https://user-images.githubusercontent.com/209150/227803736-7446e8e1-39d7-4078-8d5d-d1aa12298a5a.jpeg)


Hope this helps
