### ISSUE TITLE
[Teensy3.6] Some keys are not recognized on MacOS

### ISSUE THREAD

**Issue by Sanic** [kinx-project/kint#18]
See also https://github.com/kinx-project/kint/issues/16#issuecomment-748665978

It seems that the Teensy 3.6 version of this controller might behave weirdly on MacOS:
  - Some keys are not detected properly (For example the thumb keys for delete, enter, etc.)
  - Keys are only activated if another key close to it is pressed (same column?)

Is there somebody who uses the teensy 3.6 variant of this controller with a mac successfully?

**Comment by stapelberg** [comment]
I just tested my Teensy 3.6 Kinesis on a MacBook Air M1 running macOS Big Sur 11.0.1, and all keys seem to work perfectly fine.

You mentioned that you did a separate build with a teensy++ that worked. I assume you have been using both controllers in the same keyboard, so we can likely exclude keyboard issues.

Can you double-check all soldering joints on the affected board? Applying some extra flux in liquid form, if you have it, or just a little fresh solder and re-heating each solder joint will usually help.

**Comment by stapelberg** [comment]
I’ll close this as there were no other reports of this issue, and I couldn’t reproduce it.
