### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by ecraven** [kinx-project/kint#33]
I've recently run into the following problem:
```
Error: %s: %s ('ImportError', ImportError("cannot import name 'format_ansi' from 'milc' (/usr/lib/python3.9/site-packages/milc/__init__.py)"))
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/qmk_cli/script_qmk.py", line 74, in main
    import qmk.cli  # noqa
  File "/home/nex/qmk_firmware/lib/python/qmk/cli/__init__.py", line 13, in <module>
    from . import doctor
  File "/home/nex/qmk_firmware/lib/python/qmk/cli/doctor.py", line 13, in <module>
    from qmk.questions import yesno
  File "/home/nex/qmk_firmware/lib/python/qmk/questions.py", line 4, in <module>
    from milc import cli, format_ansi
ImportError: cannot import name 'format_ansi' from 'milc' (/usr/lib/python3.9/site-packages/milc/__init__.py)
```
This seems to be a problem with recent versions of milc, which upstream has fixed. I've not been successful in trying to get the kint36 working by copying things into upstream QMK.

Is there any chance of either updating this fork to current upstream, or even better, getting kint36 merged into QMK proper?

Thanks for any help with this!

**Comment by stapelberg** [comment]
> Is there any chance of either updating this fork to current upstream, or even better, getting kint36 merged into QMK proper?

kint36 has already been merged into QMK proper. You need to use QMK’s `develop` branch, though.

**Comment by ecraven** [comment]
perfect, thank you!
