### ISSUE TITLE
Teensy 4.1 With or without headers

### ISSUE THREAD

**Issue by kieran-mace** [kinx-project/kint#43]
This is my first project. So apologies for the noob questions:

I picked up the Teeny 4.1 with headers: https://www.digikey.com/en/products/detail/sparkfun-electronics/DEV-16996/13158152

Is this going to be a problem? should I have ordered it without?

**Comment by stapelberg** [comment]
You need the version without headers indeed. See the soldering instructions: https://github.com/kinx-project/kint#soldering-instructions-for-the-teensy-3x-or-4x, and/or the video: https://youtu.be/I0kwQbnhlfk?t=5880 (from 1:38:00 to 3:33:53)
