### ISSUE TITLE
KB500, but different thumb connections

### ISSUE THREAD

**Issue by shigmas** [kinx-project/kint#48]
I have a KB500USB (I guess I have a non-USB one in storage).

The PCB's for the thumbs are connected directly to the board. Is it possible to cut them and connect to the molex connectors on the kinT board?

**Comment by stapelberg** [comment]
Does https://github.com/kinx-project/kint/issues/11#issuecomment-679308539 answer your question?

**Comment by shigmas** [comment]
Aha! Yes. Certainly not as pretty as the molex, but it might keep me using this 20 year old keyboard.
I should have looked through the closed issues. Thanks!
