### ISSUE TITLE
malfunctioning "b" COL_3

### ISSUE THREAD

**Issue by mbenecke** [kinx-project/kint#56]
Hi,

thanks for your work, i would love the Idea to have qmk running on my Kinesis ADV 500.

I was following your guides for set up the Teensy 4.1 as straight as possible.
Now I see me in a similar situation as [landakram in issue 16](https://github.com/kinx-project/kint/issues/16#issuecomment-708060221)
COL_3 troubles me, it is so hard that the Teensy is sometimes reset and I have to flash it again. It prints out 1000nds of characters. 

I was thinking, "ok, lets check the connections", I used an USB Power Brick, so no OS driver in charge and hooked up my Ozi

I check "20" and G,
- it shows no difference if any key is connected or not, a straight line for 3V. Which is OK for me.
- it doesnt care if i press the upper 2 character lines, great.
- If a press keys in the bottom row (z-v;n-?) it shows this behavior:  A sign of the matrix scan I assume?
   ![IMG_019](https://user-images.githubusercontent.com/23499616/177785365-231a3464-c6f7-41dc-9002-fdcb446419a3.jpg)
- Buf if I press "b" it locks like this, which looks not ok:
  ![IMG_020](https://user-images.githubusercontent.com/23499616/177785370-4fd3c825-a75d-4fc1-a67b-43aa333550c6.jpg)

Any advice how to proceed? Any other measurements you suggest?

**Comment by stapelberg** [comment]
Hey 👋

Usually, such issues are soldering point issues. Double check all soldering points, either by carefully inspecting them under bright light, or by just re-soldering all of them just in case. 

If nothing else helps, maybe soldering another one is the easiest way to a working board for now.
