### ISSUE TITLE
Error Flashing 4.0

### ISSUE THREAD

**Issue by 222Phoenix** [kinx-project/kint#63]
Just finished soldering the pcb & teensy 4.0 but I'm not able to flash it.

I tried the default one (kinesis_kint41_default.hex)
https://github.com/kinx-project/kint/tree/main/default-firmware
and also my own compiled via QMK MYSYS

I tried both teensy loader and QMK toolbox on different computers and different USB cables. 

This is the error when trying to flash the default hex via QMK Toolbox:

*** Halfkay device connected (HidUsb): (Standard system devices) USB Input Device (16C0:0478:0108)
*** Attempting to flash, please don't remove device
>>> teensy_loader_cli.exe -mmcu=atmega32u4 "C:\Users\admin\Desktop\kinesis_kint41_default.hex" -v
    Teensy Loader, Command Line, Version 2.1
    Warning, HEX parse error line 1
    error reading intel hex file "C:\Users\admin\Desktop\kinesis_kint41_default.hex"

**Comment by stapelberg** [comment]
In https://github.com/kinx-project/kint/issues/62, someone mentioned that flashing from Windows might have issues.

Can you try flashing from a computer running Linux? You can start your computer from a live linux USB stick.

**Comment by 222Phoenix** [comment]
Just tried in Ubuntu. I don't see an error, so it seems like it worked, but the keys still do nothing. Wonder if it's a bad Teensy. Flashing the LED blink program via Teensy loader did work though. 

qmk flash -kb kinesis/kint41 -km default
Ψ Compiling keymap with gmake --jobs=1 kinesis/kint41:default:flash

QMK Firmware 0.20.1
⚠ kinesis/kint41: IGNORE_MOD_TAP_INTERRUPT in config.h is deprecated and will be removed at a later date
Making kinesis/kint41 with keymap default and target flash

⚠ kinesis/kint41: IGNORE_MOD_TAP_INTERRUPT in config.h is deprecated and will be removed at a later date
arm-none-eabi-gcc (15:10.3-2021.07-4) 10.3.1 20210621 (release)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Size before:
   text	   data	    bss	    dec	    hex	filename
      0	  40568	      0	  40568	   9e78	kinesis_kint41_default.bin

Compiling: quantum/command.c                                                                        [OK]
Linking: .build/kinesis_kint41_default.elf                                                          [OK]
Creating binary load file for flashing: .build/kinesis_kint41_default.bin                           [OK]
Creating load file for flashing: .build/kinesis_kint41_default.hex                                  [OK]

Size after:
   text	   data	    bss	    dec	    hex	filename
      0	  40568	      0	  40568	   9e78	kinesis_kint41_default.bin

Copying kinesis_kint41_default.bin to qmk_firmware folder                                           [OK]
Flashing for bootloader: halfkay
Teensy Loader, Command Line, Version 2.2
Read ".build/kinesis_kint41_default.hex": 40568 bytes, 2.0% usage
Found HalfKay Bootloader
Programming......................................
Booting

**Comment by stapelberg** [comment]
You can try the prebuilt firmware images on https://github.com/kinx-project/kint/ to see if it’s a problem with your build or with your teensy.

**Comment by stapelberg** [comment]
> Teensy Loader won't flash the default firmware. In Verbose mode, opening the default firmware (kinesis_kint41_default.hex from https://github.com/kinx-project/kint/tree/main/default-firmware) shows:
> 
> 16:39:34.103 (loader): Verbose Info event 16:39:42.453 (loader): Open File event 16:39:45.391 (loader): ihex: parse error line 1 16:39:45.391 (loader): ihex: parse error line 2
> 
> The program button is grayed out. The status bar says: kinesis_kint41_default.hex (unreadable)

Sorry for the late reply.

I cannot reproduce this issue.

When I download the default firmware file, I can flash it without issues to a Teensy 4.1:

```
% wget https://raw.githubusercontent.com/kinx-project/kint/main/default-firmware/kinesis_kint41_default.hex
--2023-05-01 19:24:17--  https://raw.githubusercontent.com/kinx-project/kint/main/default-firmware/kinesis_kint41_default.hex
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8001::154, 2606:50c0:8002::154, 2606:50c0:8000::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8001::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 105050 (103K) [text/plain]
Saving to: ‘kinesis_kint41_default.hex’

kinesis_kint41_default.hex                      100%[====================================================================================================>] 102,59K  --.-KB/s    in 0,01s   

2023-05-01 19:24:17 (7,52 MB/s) - ‘kinesis_kint41_default.hex’ saved [105050/105050]

% teensy-loader-cli -mmcu=imxrt1062 -w -v kinesis_kint41_default.hex                                       
Teensy Loader, Command Line, Version 2.2
Read "kinesis_kint41_default.hex": 37322 bytes, 1.8% usage
Waiting for Teensy device...
 (hint: press the reset button)
Found HalfKay Bootloader
Read "kinesis_kint41_default.hex": 37322 bytes, 1.8% usage
Programming...................................
Booting
```

I’m strongly suspecting that the issue you’re running into is caused by how you downloaded the file. I suggest downloading the repository as a zip file from GitHub and then unpacking that.
